# Generated by Django 3.1.2 on 2020-10-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='tag_title',
        ),
    ]
