# Generated by Django 3.1.1 on 2020-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('body', models.TextField(verbose_name='Текст')),
                ('date_pub', models.DateTimeField(null=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
