# Generated by Django 3.1.1 on 2020-09-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_truncate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылка на обложку'),
        ),
    ]
