# Generated by Django 3.1.2 on 2020-10-06 06:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201006_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
