# Generated by Django 3.1.2 on 2020-10-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
