# Generated by Django 3.1.1 on 2020-10-08 07:18

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=martor.models.MartorField(verbose_name='Текст поста'),
        ),
    ]
