# Generated by Django 3.1.2 on 2020-10-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
    ]
