# Generated by Django 3.1.2 on 2020-10-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_hidden',
            field=models.BooleanField(default=True, verbose_name='Скрыть e-mail'),
        ),
    ]
